import "../styles/globals.scss";
import RootProviders from "./RootProviders";

export const metadata = {
  title: "CSS Art Gallery",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <RootProviders>
      <html lang="en">
        <body>{children}</body>
      </html>
    </RootProviders>
  );
}
